# Site settings
title: 力奥的技术博客
email: 42316099@qq.com
description: 专注于互联网相关技术
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.gopersist.com" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/index.html

# Build settings
markdown: kramdown

# comments
comments:
    provider: duoshuo
    duoshuo:
        short_name: gopersist

# 分页
paginate: 10
paginate_path: "page:num"

plugins: [jekyll-paginate]

# 代码高亮
highlighter: rouge
